/*
 *	AI 类型定义
 */
#ifndef ai_type_h__
#define ai_type_h__

#define AI_CONDITION_SATISFY 1
#define AI_CONDITION_TIMER 2
#define AI_CONDITION_CAN_ATTACK 3
#define AI_CONDITION_ENEMY_IN_RANGE 4
#define AI_CONDITION_TRIGGER_IN_RANGE 5
#define AI_CONDITION_IN_SKILL_RANGE 6
#define AI_CONDITION_IN_CITY 7
#define AI_CONDITION_SKILL_IN_CD 8
#define AI_CONDITION_LACK_HP 9
#define AI_CONDITION_LACK_MP 10
#define AI_CONDITION_ON_HIT 11
#define AI_CONDITION_ON_STATE 12
#define AI_CONDITION_LOST_TARGET 13
#define AI_CONDITION_ENEMY_EXIST 14
#define AI_CONDITION_FINISH_PATH 15
#define AI_CONDITION_MASTER_ON_HIT 16
#define AI_CONDITION_MASTER_IN_RANGE 17
#define AI_CONDITION_MASTER_ATTACK 18
#define AI_CONDITION_BATTLE_PET_ALIVE 19
#define AI_CONDITION_SUMMON_PET_NUM 20
#define AI_CONDITION_PET_LIFE 21
#define AI_CONDITION_MASTER_IS_IDLE 22
#define AI_CONDITION_FIND_ENEMY 31
#define AI_ACTION_ACCEPT_TASK 1
#define AI_ACTION_ACTIVATE_TRIGGER 2
#define AI_ACTION_CHOOSE_SKILL 3
#define AI_ACTION_MOVE_RANDOM 4
#define AI_ACTION_MOVE_TO 5
#define AI_ACTION_PATHING 6
#define AI_ACTION_ADD_HP 7
#define AI_ACTION_ADD_MP 8
#define AI_ACTION_SEEK_OBJECT 9
#define AI_ACTION_SKILL_TO 10
#define AI_ACTION_TELEPORT 11
#define AI_ACTION_PLAY_RANDOM 12
#define AI_ACTION_FLEE 13
#define AI_ACTION_STOP 14
#define AI_ACTION_SET_AI 15
#define AI_ACTION_BACK_AI 16
#define AI_ACTION_PLAY_IDLE 17
#define AI_ACTION_FOLLOW_MASTER 18

const uint32    AI_UPDATE_TIME = 100;       // AI逻辑周期
const uint32    AI_SLOW_UPDATE_TICK = 20;   // AI慢时钟周期(帧数)

#endif // ai_type_h__
